CREATE TABLE "account" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login" varchar NOT NULL,
  "username" varchar NOT NULL,
  "created" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "snippets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" integer NOT NULL,
  "title" varchar NOT NULL,
  "content" varchar NOT NULL,
  "created" timestamptz NOT NULL DEFAULT 'now()'
);

ALTER TABLE "snippets" ADD FOREIGN KEY ("account_id") REFERENCES "account" ("id");