// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID       int32     `json:"id"`
	Login    string    `json:"login"`
	Username string    `json:"username"`
	Created  time.Time `json:"created"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	Created      time.Time `json:"created"`
}

type Snippet struct {
	ID        int32     `json:"id"`
	AccountID int32     `json:"account_id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Created   time.Time `json:"created"`
}

type User struct {
	Name              string    `json:"name"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	Created           time.Time `json:"created"`
	IsEmailVerified   bool      `json:"is_email_verified"`
}

type VerifyEmail struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	IsUsedSc   bool      `json:"is_used_sc"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiredAt  time.Time `json:"expired_at"`
}
