// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"
)

type Account struct {
	ID       int32     `json:"id"`
	Login    string    `json:"login"`
	Username string    `json:"username"`
	Created  time.Time `json:"created"`
}

type Snippet struct {
	ID        int32     `json:"id"`
	AccountID int32     `json:"account_id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Created   time.Time `json:"created"`
}

type User struct {
	Name              string    `json:"name"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	Created           time.Time `json:"created"`
}
