// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"
)

type Snippet struct {
	ID      int32     `json:"id"`
	UserID  int32     `json:"user_id"`
	Title   string    `json:"title"`
	Content string    `json:"content"`
	Created time.Time `json:"created"`
}

type User struct {
	ID       int32     `json:"id"`
	Login    string    `json:"login"`
	Username string    `json:"username"`
	Created  time.Time `json:"created"`
}
