// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateSnippet(ctx context.Context, arg CreateSnippetParams) (Snippet, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSnippet(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetSnippet(ctx context.Context, id int32) (Snippet, error)
	GetUser(ctx context.Context, id int32) (User, error)
	ListSnippets(ctx context.Context, arg ListSnippetsParams) ([]Snippet, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
