// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: verify_email.sql

package db

import (
	"context"
)

const createVerifyEmail = `-- name: CreateVerifyEmail :one
INSERT INTO verify_emails (
    name,
    email,
    secret_code
)   VALUES (
    $1, $2, $3
)   RETURNING id, name, email, secret_code, is_used_sc, created_at, expired_at
`

type CreateVerifyEmailParams struct {
	Name       string `json:"name"`
	Email      string `json:"email"`
	SecretCode string `json:"secret_code"`
}

func (q *Queries) CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error) {
	row := q.db.QueryRowContext(ctx, createVerifyEmail, arg.Name, arg.Email, arg.SecretCode)
	var i VerifyEmail
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.SecretCode,
		&i.IsUsedSc,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}
