CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login" varchar UNIQUE NOT NULL,
  "username" varchar NOT NULL,
  "created" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "snippets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "title" varchar NOT NULL,
  "content" varchar NOT NULL,
  "created" timestamptz NOT NULL DEFAULT 'now()'
);

ALTER TABLE "snippets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");